[package]
name = "latex_compile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
notify = "6.1.1"
notify-debouncer-mini = "0.4.1"
