[package]
name = "every_day_execution"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rscx = "0.1.11"
tokio = "1.34.0"
warp = "0.3.6"
